# Generated by Django 3.0 on 2022-06-25 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('porteiros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NA_RUA', 'Veículo fora da empresa'), ('NA_EMPRESA', 'Veículo na empresa')], default='AGUARDANDO', max_length=10, verbose_name='Status')),
                ('nome_motorista', models.CharField(max_length=194, verbose_name='Nome motorista')),
                ('veiculo', models.CharField(choices=[('GOL', 'Gol'), ('SAVEIRO', 'Saveiro')], default='SAVEIRO', max_length=50, verbose_name='Carro')),
                ('destino', models.CharField(max_length=50, verbose_name='Destino da saida')),
                ('placa_veiculo', models.CharField(blank=True, max_length=7, null=True, verbose_name='Placa do veículo')),
                ('horario_chegada', models.DateTimeField(auto_now_add=True, verbose_name='Horário de chegada na portaria')),
                ('horario_saida', models.DateTimeField(blank=True, null=True, verbose_name='Horário de saida')),
                ('responsavel', models.CharField(blank=True, max_length=194, verbose_name='Responsável pela saida do veiculo')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='porteiros.Porteiro', verbose_name='Porteiro responsável pelo registro')),
            ],
            options={
                'verbose_name': 'Veiculo',
                'verbose_name_plural': 'Veiculos',
                'db_table': 'veiculo',
            },
        ),
    ]
