# Generated by Django 3.0 on 2022-06-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='status',
            field=models.CharField(choices=[('NA_RUA', 'Veículo fora da empresa'), ('NA_EMPRESA', 'Veículo na empresa')], default='NA_RUA', max_length=10, verbose_name='Status'),
        ),
    ]
