# Generated by Django 3.0 on 2022-06-26 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0002_auto_20220626_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='horario_chegada',
            field=models.CharField(max_length=50, verbose_name='Horário de chegada na portaria'),
        ),
    ]
