# Generated by Django 3.0 on 2022-06-26 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0003_auto_20220626_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='horario_chegada',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Horário de chegada na portaria'),
        ),
    ]
