# Generated by Django 3.0 on 2022-06-27 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0004_auto_20220626_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='horario_chegada',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='horario_retorno',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Horário de retorno a empresa'),
        ),
    ]
