# Generated by Django 3.0 on 2022-06-27 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0005_auto_20220626_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='horario_retorno',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário de retorno a empresa'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='horario_saida',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário de saida'),
        ),
    ]
