# Generated by Django 3.0 on 2022-06-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0003_auto_20220622_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitante',
            name='numero_casa',
        ),
        migrations.AddField(
            model_name='visitante',
            name='setor',
            field=models.CharField(choices=[('MANUTENCAO', 'Manutenção'), ('RH', 'Rh'), ('DIRETORIA', 'Diretoria'), ('ALMOXARIFADO', 'Almoxarifado'), ('ACABAMENTO', 'Acabamento'), ('PRODUCAO', 'Produção'), ('SESMT', 'Segurança do Trabalho')], default='ALMOXARIFADO', max_length=20, verbose_name='Setor a ser visitada'),
        ),
    ]
