# Generated by Django 3.0 on 2022-06-26 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0004_auto_20220622_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitante',
            name='data_nascimento',
        ),
    ]
