# Generated by Django 3.0 on 2022-06-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0005_remove_visitante_data_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitante',
            name='empresa_visitante',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Empresa'),
        ),
    ]
